# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  #    param_fetcher_listener:  true
  #    allowed_methods_listener:  true
  #    routing_loader: true
  #    view:
  #        view_response_listener:  true
  #  exception:
  #    enabled: true
  #    exception_controller: \App\Controller\ExceptionController::exceptionAction
  #    codes:
  #      \App\Exception\PublicException: 404
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: ^/, prefer_extension: false, fallback_format: json, priorities: [ json ] }
  serializer:
    version: null
    groups: [ ]
    serialize_null: true
